# Generated by Django 3.2.5 on 2021-08-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210725_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.TextField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
