# Generated by Django 3.2.5 on 2021-08-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
